lang =
    en:
        "about": "About"
        "source": "Source"
        "changelog": "Change log"
        "motto": "create, share, like, comment"
        "fork": "Fork"
        "download": "Download"
        "like": "Like"
        "likes": "likes"
        "like1": "like"
        "views": "views"
        "view1": "view"
        "newcode": "New Code"
        "save": "Save"
        "aboutpage": "LookAtMyCode is a system where you can store text for a certain period of time. The system is mainly used by programmers to store, share and like pieces of sources code"
        "changelogpage": "<ul><li>1.0 - init version</li></ul>"
        "created": "Created by"
    ru:
        "about": "О проекте"
        "source": "Исходные коды"
        "changelog": "История изменений"
        "motto": "создавай, делись, одобряй, комментируй"
        "fork": "Ответвиться"
        "download": "Скачать"
        "like": "Одобряю"
        "likes": "одобрений"
        "like1": "одобрение"
        "views": "просмотров"
        "view1": "просмотр"
        "newcode": "Новый код"
        "save": "Сохранить"
        "aboutpage": "LookAtMyCode &mdash; это система для публикации, комментирования и исследования исходных кодов. Система может быть развёрнута в рамках компании или использоваться в глобальной сети интернет."
        "changelogpage": "<ul><li>1.0 - первая версия</li></ul>"
        "created": "Создал"

